
//input ports
add mapped point clk clk -type PI PI
add mapped point valid_in valid_in -type PI PI
add mapped point xin_re[15] xin_re[15] -type PI PI
add mapped point xin_re[14] xin_re[14] -type PI PI
add mapped point xin_re[13] xin_re[13] -type PI PI
add mapped point xin_re[12] xin_re[12] -type PI PI
add mapped point xin_re[11] xin_re[11] -type PI PI
add mapped point xin_re[10] xin_re[10] -type PI PI
add mapped point xin_re[9] xin_re[9] -type PI PI
add mapped point xin_re[8] xin_re[8] -type PI PI
add mapped point xin_re[7] xin_re[7] -type PI PI
add mapped point xin_re[6] xin_re[6] -type PI PI
add mapped point xin_re[5] xin_re[5] -type PI PI
add mapped point xin_re[4] xin_re[4] -type PI PI
add mapped point xin_re[3] xin_re[3] -type PI PI
add mapped point xin_re[2] xin_re[2] -type PI PI
add mapped point xin_re[1] xin_re[1] -type PI PI
add mapped point xin_re[0] xin_re[0] -type PI PI
add mapped point xin_im[15] xin_im[15] -type PI PI
add mapped point xin_im[14] xin_im[14] -type PI PI
add mapped point xin_im[13] xin_im[13] -type PI PI
add mapped point xin_im[12] xin_im[12] -type PI PI
add mapped point xin_im[11] xin_im[11] -type PI PI
add mapped point xin_im[10] xin_im[10] -type PI PI
add mapped point xin_im[9] xin_im[9] -type PI PI
add mapped point xin_im[8] xin_im[8] -type PI PI
add mapped point xin_im[7] xin_im[7] -type PI PI
add mapped point xin_im[6] xin_im[6] -type PI PI
add mapped point xin_im[5] xin_im[5] -type PI PI
add mapped point xin_im[4] xin_im[4] -type PI PI
add mapped point xin_im[3] xin_im[3] -type PI PI
add mapped point xin_im[2] xin_im[2] -type PI PI
add mapped point xin_im[1] xin_im[1] -type PI PI
add mapped point xin_im[0] xin_im[0] -type PI PI

//output ports
add mapped point xout_re[15] xout_re[15] -type PO PO
add mapped point xout_re[14] xout_re[14] -type PO PO
add mapped point xout_re[13] xout_re[13] -type PO PO
add mapped point xout_re[12] xout_re[12] -type PO PO
add mapped point xout_re[11] xout_re[11] -type PO PO
add mapped point xout_re[10] xout_re[10] -type PO PO
add mapped point xout_re[9] xout_re[9] -type PO PO
add mapped point xout_re[8] xout_re[8] -type PO PO
add mapped point xout_re[7] xout_re[7] -type PO PO
add mapped point xout_re[6] xout_re[6] -type PO PO
add mapped point xout_re[5] xout_re[5] -type PO PO
add mapped point xout_re[4] xout_re[4] -type PO PO
add mapped point xout_re[3] xout_re[3] -type PO PO
add mapped point xout_re[2] xout_re[2] -type PO PO
add mapped point xout_re[1] xout_re[1] -type PO PO
add mapped point xout_re[0] xout_re[0] -type PO PO
add mapped point xout_im[15] xout_im[15] -type PO PO
add mapped point xout_im[14] xout_im[14] -type PO PO
add mapped point xout_im[13] xout_im[13] -type PO PO
add mapped point xout_im[12] xout_im[12] -type PO PO
add mapped point xout_im[11] xout_im[11] -type PO PO
add mapped point xout_im[10] xout_im[10] -type PO PO
add mapped point xout_im[9] xout_im[9] -type PO PO
add mapped point xout_im[8] xout_im[8] -type PO PO
add mapped point xout_im[7] xout_im[7] -type PO PO
add mapped point xout_im[6] xout_im[6] -type PO PO
add mapped point xout_im[5] xout_im[5] -type PO PO
add mapped point xout_im[4] xout_im[4] -type PO PO
add mapped point xout_im[3] xout_im[3] -type PO PO
add mapped point xout_im[2] xout_im[2] -type PO PO
add mapped point xout_im[1] xout_im[1] -type PO PO
add mapped point xout_im[0] xout_im[0] -type PO PO
add mapped point valid_out valid_out -type PO PO

//inout ports




//Sequential Pins
add mapped point STAGE2/valid_out/q STAGE2/valid_out_reg/Q -type DFF DFF
add mapped point STAGE2/cnt[0]/q STAGE2/cnt_reg[0]/Q -type DFF DFF
add mapped point STAGE2/cnt[1]/q STAGE2/cnt_reg[1]/Q -type DFF DFF
add mapped point STAGE2/cnt[3]/q STAGE2/cnt_reg[3]/Q -type DFF DFF
add mapped point STAGE2/d_re[1][0]/q STAGE2/d_re_reg[1][0]/Q -type DFF DFF
add mapped point STAGE2/d_re[1][3]/q STAGE2/d_re_reg[1][3]/Q -type DFF DFF
add mapped point STAGE2/d_re[1][6]/q STAGE2/d_re_reg[1][6]/Q -type DFF DFF
add mapped point STAGE2/d_re[1][7]/q STAGE2/d_re_reg[1][7]/Q -type DFF DFF
add mapped point STAGE2/d_re[1][9]/q STAGE2/d_re_reg[1][9]/Q -type DFF DFF
add mapped point STAGE2/d_re[1][10]/q STAGE2/d_re_reg[1][10]/Q -type DFF DFF
add mapped point STAGE2/d_re[1][11]/q STAGE2/d_re_reg[1][11]/Q -type DFF DFF
add mapped point STAGE2/d_re[1][12]/q STAGE2/d_re_reg[1][12]/Q -type DFF DFF
add mapped point STAGE2/d_re[1][15]/q STAGE2/d_re_reg[1][15]/Q -type DFF DFF
add mapped point STAGE2/xout_im[0]/q STAGE2/xout_im_reg[0]/Q -type DFF DFF
add mapped point STAGE2/xout_im[1]/q STAGE2/xout_im_reg[1]/Q -type DFF DFF
add mapped point STAGE2/xout_im[2]/q STAGE2/xout_im_reg[2]/Q -type DFF DFF
add mapped point STAGE2/xout_im[3]/q STAGE2/xout_im_reg[3]/Q -type DFF DFF
add mapped point STAGE2/xout_im[4]/q STAGE2/xout_im_reg[4]/Q -type DFF DFF
add mapped point STAGE2/xout_im[5]/q STAGE2/xout_im_reg[5]/Q -type DFF DFF
add mapped point STAGE2/xout_im[6]/q STAGE2/xout_im_reg[6]/Q -type DFF DFF
add mapped point STAGE2/xout_im[7]/q STAGE2/xout_im_reg[7]/Q -type DFF DFF
add mapped point STAGE2/xout_im[8]/q STAGE2/xout_im_reg[8]/Q -type DFF DFF
add mapped point STAGE2/xout_im[9]/q STAGE2/xout_im_reg[9]/Q -type DFF DFF
add mapped point STAGE2/xout_im[10]/q STAGE2/xout_im_reg[10]/Q -type DFF DFF
add mapped point STAGE2/xout_im[11]/q STAGE2/xout_im_reg[11]/Q -type DFF DFF
add mapped point STAGE2/xout_im[12]/q STAGE2/xout_im_reg[12]/Q -type DFF DFF
add mapped point STAGE2/xout_im[13]/q STAGE2/xout_im_reg[13]/Q -type DFF DFF
add mapped point STAGE2/xout_im[14]/q STAGE2/xout_im_reg[14]/Q -type DFF DFF
add mapped point STAGE2/xout_im[15]/q STAGE2/xout_im_reg[15]/Q -type DFF DFF
add mapped point STAGE2/xout_re[0]/q STAGE2/xout_re_reg[0]/Q -type DFF DFF
add mapped point STAGE2/xout_re[1]/q STAGE2/xout_re_reg[1]/Q -type DFF DFF
add mapped point STAGE2/xout_re[2]/q STAGE2/xout_re_reg[2]/Q -type DFF DFF
add mapped point STAGE2/xout_re[3]/q STAGE2/xout_re_reg[3]/Q -type DFF DFF
add mapped point STAGE2/xout_re[4]/q STAGE2/xout_re_reg[4]/Q -type DFF DFF
add mapped point STAGE2/xout_re[5]/q STAGE2/xout_re_reg[5]/Q -type DFF DFF
add mapped point STAGE2/xout_re[6]/q STAGE2/xout_re_reg[6]/Q -type DFF DFF
add mapped point STAGE2/xout_re[7]/q STAGE2/xout_re_reg[7]/Q -type DFF DFF
add mapped point STAGE2/xout_re[8]/q STAGE2/xout_re_reg[8]/Q -type DFF DFF
add mapped point STAGE2/xout_re[9]/q STAGE2/xout_re_reg[9]/Q -type DFF DFF
add mapped point STAGE2/xout_re[10]/q STAGE2/xout_re_reg[10]/Q -type DFF DFF
add mapped point STAGE2/xout_re[11]/q STAGE2/xout_re_reg[11]/Q -type DFF DFF
add mapped point STAGE2/xout_re[12]/q STAGE2/xout_re_reg[12]/Q -type DFF DFF
add mapped point STAGE2/xout_re[13]/q STAGE2/xout_re_reg[13]/Q -type DFF DFF
add mapped point STAGE2/xout_re[14]/q STAGE2/xout_re_reg[14]/Q -type DFF DFF
add mapped point STAGE2/xout_re[15]/q STAGE2/xout_re_reg[15]/Q -type DFF DFF
add mapped point STAGE2/cnt[2]/q STAGE2/cnt_reg[2]/Q -type DFF DFF
add mapped point STAGE2/d_im[0][0]/q STAGE2/d_im_reg[0][0]/Q -type DFF DFF
add mapped point STAGE2/d_im[0][1]/q STAGE2/d_im_reg[0][1]/Q -type DFF DFF
add mapped point STAGE2/d_im[0][2]/q STAGE2/d_im_reg[0][2]/Q -type DFF DFF
add mapped point STAGE2/d_im[0][3]/q STAGE2/d_im_reg[0][3]/Q -type DFF DFF
add mapped point STAGE2/d_im[0][4]/q STAGE2/d_im_reg[0][4]/Q -type DFF DFF
add mapped point STAGE2/d_im[0][5]/q STAGE2/d_im_reg[0][5]/Q -type DFF DFF
add mapped point STAGE2/d_im[0][6]/q STAGE2/d_im_reg[0][6]/Q -type DFF DFF
add mapped point STAGE2/d_im[0][7]/q STAGE2/d_im_reg[0][7]/Q -type DFF DFF
add mapped point STAGE2/d_im[0][8]/q STAGE2/d_im_reg[0][8]/Q -type DFF DFF
add mapped point STAGE2/d_im[0][9]/q STAGE2/d_im_reg[0][9]/Q -type DFF DFF
add mapped point STAGE2/d_im[0][10]/q STAGE2/d_im_reg[0][10]/Q -type DFF DFF
add mapped point STAGE2/d_im[0][11]/q STAGE2/d_im_reg[0][11]/Q -type DFF DFF
add mapped point STAGE2/d_im[0][12]/q STAGE2/d_im_reg[0][12]/Q -type DFF DFF
add mapped point STAGE2/d_im[0][13]/q STAGE2/d_im_reg[0][13]/Q -type DFF DFF
add mapped point STAGE2/d_im[0][14]/q STAGE2/d_im_reg[0][14]/Q -type DFF DFF
add mapped point STAGE2/d_im[0][15]/q STAGE2/d_im_reg[0][15]/Q -type DFF DFF
add mapped point STAGE2/d_im[1][0]/q STAGE2/d_im_reg[1][0]/Q -type DFF DFF
add mapped point STAGE2/d_im[1][1]/q STAGE2/d_im_reg[1][1]/Q -type DFF DFF
add mapped point STAGE2/d_im[1][2]/q STAGE2/d_im_reg[1][2]/Q -type DFF DFF
add mapped point STAGE2/d_im[1][3]/q STAGE2/d_im_reg[1][3]/Q -type DFF DFF
add mapped point STAGE2/d_im[1][4]/q STAGE2/d_im_reg[1][4]/Q -type DFF DFF
add mapped point STAGE2/d_im[1][5]/q STAGE2/d_im_reg[1][5]/Q -type DFF DFF
add mapped point STAGE2/d_im[1][6]/q STAGE2/d_im_reg[1][6]/Q -type DFF DFF
add mapped point STAGE2/d_im[1][7]/q STAGE2/d_im_reg[1][7]/Q -type DFF DFF
add mapped point STAGE2/d_im[1][8]/q STAGE2/d_im_reg[1][8]/Q -type DFF DFF
add mapped point STAGE2/d_im[1][9]/q STAGE2/d_im_reg[1][9]/Q -type DFF DFF
add mapped point STAGE2/d_im[1][10]/q STAGE2/d_im_reg[1][10]/Q -type DFF DFF
add mapped point STAGE2/d_im[1][11]/q STAGE2/d_im_reg[1][11]/Q -type DFF DFF
add mapped point STAGE2/d_im[1][12]/q STAGE2/d_im_reg[1][12]/Q -type DFF DFF
add mapped point STAGE2/d_im[1][13]/q STAGE2/d_im_reg[1][13]/Q -type DFF DFF
add mapped point STAGE2/d_im[1][14]/q STAGE2/d_im_reg[1][14]/Q -type DFF DFF
add mapped point STAGE2/d_im[1][15]/q STAGE2/d_im_reg[1][15]/Q -type DFF DFF
add mapped point STAGE2/d_re[0][0]/q STAGE2/d_re_reg[0][0]/Q -type DFF DFF
add mapped point STAGE2/d_re[0][1]/q STAGE2/d_re_reg[0][1]/Q -type DFF DFF
add mapped point STAGE2/d_re[0][2]/q STAGE2/d_re_reg[0][2]/Q -type DFF DFF
add mapped point STAGE2/d_re[0][3]/q STAGE2/d_re_reg[0][3]/Q -type DFF DFF
add mapped point STAGE2/d_re[0][4]/q STAGE2/d_re_reg[0][4]/Q -type DFF DFF
add mapped point STAGE2/d_re[0][5]/q STAGE2/d_re_reg[0][5]/Q -type DFF DFF
add mapped point STAGE2/d_re[0][6]/q STAGE2/d_re_reg[0][6]/Q -type DFF DFF
add mapped point STAGE2/d_re[0][7]/q STAGE2/d_re_reg[0][7]/Q -type DFF DFF
add mapped point STAGE2/d_re[0][8]/q STAGE2/d_re_reg[0][8]/Q -type DFF DFF
add mapped point STAGE2/d_re[0][9]/q STAGE2/d_re_reg[0][9]/Q -type DFF DFF
add mapped point STAGE2/d_re[0][10]/q STAGE2/d_re_reg[0][10]/Q -type DFF DFF
add mapped point STAGE2/d_re[0][11]/q STAGE2/d_re_reg[0][11]/Q -type DFF DFF
add mapped point STAGE2/d_re[0][12]/q STAGE2/d_re_reg[0][12]/Q -type DFF DFF
add mapped point STAGE2/d_re[0][13]/q STAGE2/d_re_reg[0][13]/Q -type DFF DFF
add mapped point STAGE2/d_re[0][14]/q STAGE2/d_re_reg[0][14]/Q -type DFF DFF
add mapped point STAGE2/d_re[0][15]/q STAGE2/d_re_reg[0][15]/Q -type DFF DFF
add mapped point STAGE2/d_re[1][1]/q STAGE2/d_re_reg[1][1]/Q -type DFF DFF
add mapped point STAGE2/d_re[1][2]/q STAGE2/d_re_reg[1][2]/Q -type DFF DFF
add mapped point STAGE2/d_re[1][4]/q STAGE2/d_re_reg[1][4]/Q -type DFF DFF
add mapped point STAGE2/d_re[1][5]/q STAGE2/d_re_reg[1][5]/Q -type DFF DFF
add mapped point STAGE2/d_re[1][8]/q STAGE2/d_re_reg[1][8]/Q -type DFF DFF
add mapped point STAGE2/d_re[1][13]/q STAGE2/d_re_reg[1][13]/Q -type DFF DFF
add mapped point STAGE2/d_re[1][14]/q STAGE2/d_re_reg[1][14]/Q -type DFF DFF
add mapped point STAGE3/valid_out/q STAGE3/valid_out_reg/Q -type DFF DFF
add mapped point STAGE3/cnt[0]/q STAGE3/cnt_reg[0]/Q -type DFF DFF
add mapped point STAGE3/d_im[0][0]/q STAGE3/d_im_reg[0][0]/Q -type DFF DFF
add mapped point STAGE3/d_im[0][3]/q STAGE3/d_im_reg[0][3]/Q -type DFF DFF
add mapped point STAGE3/d_im[0][4]/q STAGE3/d_im_reg[0][4]/Q -type DFF DFF
add mapped point STAGE3/d_im[0][5]/q STAGE3/d_im_reg[0][5]/Q -type DFF DFF
add mapped point STAGE3/d_im[0][6]/q STAGE3/d_im_reg[0][6]/Q -type DFF DFF
add mapped point STAGE3/d_im[0][7]/q STAGE3/d_im_reg[0][7]/Q -type DFF DFF
add mapped point STAGE3/d_im[0][8]/q STAGE3/d_im_reg[0][8]/Q -type DFF DFF
add mapped point STAGE3/d_im[0][9]/q STAGE3/d_im_reg[0][9]/Q -type DFF DFF
add mapped point STAGE3/d_im[0][10]/q STAGE3/d_im_reg[0][10]/Q -type DFF DFF
add mapped point STAGE3/d_im[0][11]/q STAGE3/d_im_reg[0][11]/Q -type DFF DFF
add mapped point STAGE3/d_im[0][12]/q STAGE3/d_im_reg[0][12]/Q -type DFF DFF
add mapped point STAGE3/d_im[0][13]/q STAGE3/d_im_reg[0][13]/Q -type DFF DFF
add mapped point STAGE3/d_im[0][14]/q STAGE3/d_im_reg[0][14]/Q -type DFF DFF
add mapped point STAGE3/d_im[0][15]/q STAGE3/d_im_reg[0][15]/Q -type DFF DFF
add mapped point STAGE3/d_im[1][0]/q STAGE3/d_im_reg[1][0]/Q -type DFF DFF
add mapped point STAGE3/d_im[1][1]/q STAGE3/d_im_reg[1][1]/Q -type DFF DFF
add mapped point STAGE3/d_im[1][2]/q STAGE3/d_im_reg[1][2]/Q -type DFF DFF
add mapped point STAGE3/d_im[1][3]/q STAGE3/d_im_reg[1][3]/Q -type DFF DFF
add mapped point STAGE3/d_im[1][4]/q STAGE3/d_im_reg[1][4]/Q -type DFF DFF
add mapped point STAGE3/d_im[1][5]/q STAGE3/d_im_reg[1][5]/Q -type DFF DFF
add mapped point STAGE3/d_im[1][6]/q STAGE3/d_im_reg[1][6]/Q -type DFF DFF
add mapped point STAGE3/d_im[1][7]/q STAGE3/d_im_reg[1][7]/Q -type DFF DFF
add mapped point STAGE3/d_im[1][8]/q STAGE3/d_im_reg[1][8]/Q -type DFF DFF
add mapped point STAGE3/d_im[1][9]/q STAGE3/d_im_reg[1][9]/Q -type DFF DFF
add mapped point STAGE3/d_im[1][10]/q STAGE3/d_im_reg[1][10]/Q -type DFF DFF
add mapped point STAGE3/d_im[1][11]/q STAGE3/d_im_reg[1][11]/Q -type DFF DFF
add mapped point STAGE3/d_im[1][12]/q STAGE3/d_im_reg[1][12]/Q -type DFF DFF
add mapped point STAGE3/d_im[1][13]/q STAGE3/d_im_reg[1][13]/Q -type DFF DFF
add mapped point STAGE3/d_im[1][14]/q STAGE3/d_im_reg[1][14]/Q -type DFF DFF
add mapped point STAGE3/d_im[1][15]/q STAGE3/d_im_reg[1][15]/Q -type DFF DFF
add mapped point STAGE3/d_im[2][0]/q STAGE3/d_im_reg[2][0]/Q -type DFF DFF
add mapped point STAGE3/d_im[2][1]/q STAGE3/d_im_reg[2][1]/Q -type DFF DFF
add mapped point STAGE3/d_im[2][2]/q STAGE3/d_im_reg[2][2]/Q -type DFF DFF
add mapped point STAGE3/d_im[2][4]/q STAGE3/d_im_reg[2][4]/Q -type DFF DFF
add mapped point STAGE3/d_im[2][5]/q STAGE3/d_im_reg[2][5]/Q -type DFF DFF
add mapped point STAGE3/d_im[2][6]/q STAGE3/d_im_reg[2][6]/Q -type DFF DFF
add mapped point STAGE3/d_im[2][7]/q STAGE3/d_im_reg[2][7]/Q -type DFF DFF
add mapped point STAGE3/d_im[2][8]/q STAGE3/d_im_reg[2][8]/Q -type DFF DFF
add mapped point STAGE3/d_im[3][0]/q STAGE3/d_im_reg[3][0]/Q -type DFF DFF
add mapped point STAGE3/d_im[3][1]/q STAGE3/d_im_reg[3][1]/Q -type DFF DFF
add mapped point STAGE3/d_im[3][2]/q STAGE3/d_im_reg[3][2]/Q -type DFF DFF
add mapped point STAGE3/d_im[3][3]/q STAGE3/d_im_reg[3][3]/Q -type DFF DFF
add mapped point STAGE3/d_im[3][4]/q STAGE3/d_im_reg[3][4]/Q -type DFF DFF
add mapped point STAGE3/d_im[3][5]/q STAGE3/d_im_reg[3][5]/Q -type DFF DFF
add mapped point STAGE3/d_im[3][6]/q STAGE3/d_im_reg[3][6]/Q -type DFF DFF
add mapped point STAGE3/d_im[3][7]/q STAGE3/d_im_reg[3][7]/Q -type DFF DFF
add mapped point STAGE3/d_im[3][8]/q STAGE3/d_im_reg[3][8]/Q -type DFF DFF
add mapped point STAGE3/d_im[3][9]/q STAGE3/d_im_reg[3][9]/Q -type DFF DFF
add mapped point STAGE3/d_im[3][10]/q STAGE3/d_im_reg[3][10]/Q -type DFF DFF
add mapped point STAGE3/d_im[3][11]/q STAGE3/d_im_reg[3][11]/Q -type DFF DFF
add mapped point STAGE3/d_im[3][12]/q STAGE3/d_im_reg[3][12]/Q -type DFF DFF
add mapped point STAGE3/d_im[3][13]/q STAGE3/d_im_reg[3][13]/Q -type DFF DFF
add mapped point STAGE3/d_im[3][14]/q STAGE3/d_im_reg[3][14]/Q -type DFF DFF
add mapped point STAGE3/d_im[3][15]/q STAGE3/d_im_reg[3][15]/Q -type DFF DFF
add mapped point STAGE3/d_re[0][0]/q STAGE3/d_re_reg[0][0]/Q -type DFF DFF
add mapped point STAGE3/d_re[0][1]/q STAGE3/d_re_reg[0][1]/Q -type DFF DFF
add mapped point STAGE3/d_re[0][2]/q STAGE3/d_re_reg[0][2]/Q -type DFF DFF
add mapped point STAGE3/d_re[0][3]/q STAGE3/d_re_reg[0][3]/Q -type DFF DFF
add mapped point STAGE3/d_re[0][4]/q STAGE3/d_re_reg[0][4]/Q -type DFF DFF
add mapped point STAGE3/d_re[0][5]/q STAGE3/d_re_reg[0][5]/Q -type DFF DFF
add mapped point STAGE3/d_re[0][6]/q STAGE3/d_re_reg[0][6]/Q -type DFF DFF
add mapped point STAGE3/d_re[0][7]/q STAGE3/d_re_reg[0][7]/Q -type DFF DFF
add mapped point STAGE3/d_re[0][8]/q STAGE3/d_re_reg[0][8]/Q -type DFF DFF
add mapped point STAGE3/d_re[0][9]/q STAGE3/d_re_reg[0][9]/Q -type DFF DFF
add mapped point STAGE3/d_re[0][10]/q STAGE3/d_re_reg[0][10]/Q -type DFF DFF
add mapped point STAGE3/d_re[0][11]/q STAGE3/d_re_reg[0][11]/Q -type DFF DFF
add mapped point STAGE3/d_re[0][12]/q STAGE3/d_re_reg[0][12]/Q -type DFF DFF
add mapped point STAGE3/d_re[0][13]/q STAGE3/d_re_reg[0][13]/Q -type DFF DFF
add mapped point STAGE3/d_re[0][14]/q STAGE3/d_re_reg[0][14]/Q -type DFF DFF
add mapped point STAGE3/d_re[0][15]/q STAGE3/d_re_reg[0][15]/Q -type DFF DFF
add mapped point STAGE3/d_re[1][0]/q STAGE3/d_re_reg[1][0]/Q -type DFF DFF
add mapped point STAGE3/d_re[1][1]/q STAGE3/d_re_reg[1][1]/Q -type DFF DFF
add mapped point STAGE3/d_re[1][2]/q STAGE3/d_re_reg[1][2]/Q -type DFF DFF
add mapped point STAGE3/d_re[1][3]/q STAGE3/d_re_reg[1][3]/Q -type DFF DFF
add mapped point STAGE3/d_re[1][4]/q STAGE3/d_re_reg[1][4]/Q -type DFF DFF
add mapped point STAGE3/d_re[1][5]/q STAGE3/d_re_reg[1][5]/Q -type DFF DFF
add mapped point STAGE3/d_re[1][6]/q STAGE3/d_re_reg[1][6]/Q -type DFF DFF
add mapped point STAGE3/d_re[1][7]/q STAGE3/d_re_reg[1][7]/Q -type DFF DFF
add mapped point STAGE3/d_re[1][8]/q STAGE3/d_re_reg[1][8]/Q -type DFF DFF
add mapped point STAGE3/d_re[1][9]/q STAGE3/d_re_reg[1][9]/Q -type DFF DFF
add mapped point STAGE3/d_re[1][10]/q STAGE3/d_re_reg[1][10]/Q -type DFF DFF
add mapped point STAGE3/d_re[1][11]/q STAGE3/d_re_reg[1][11]/Q -type DFF DFF
add mapped point STAGE3/d_re[1][12]/q STAGE3/d_re_reg[1][12]/Q -type DFF DFF
add mapped point STAGE3/d_re[1][13]/q STAGE3/d_re_reg[1][13]/Q -type DFF DFF
add mapped point STAGE3/d_re[1][14]/q STAGE3/d_re_reg[1][14]/Q -type DFF DFF
add mapped point STAGE3/d_re[1][15]/q STAGE3/d_re_reg[1][15]/Q -type DFF DFF
add mapped point STAGE3/d_re[2][5]/q STAGE3/d_re_reg[2][5]/Q -type DFF DFF
add mapped point STAGE3/d_re[2][7]/q STAGE3/d_re_reg[2][7]/Q -type DFF DFF
add mapped point STAGE3/d_re[2][9]/q STAGE3/d_re_reg[2][9]/Q -type DFF DFF
add mapped point STAGE3/d_re[2][11]/q STAGE3/d_re_reg[2][11]/Q -type DFF DFF
add mapped point STAGE3/d_re[2][13]/q STAGE3/d_re_reg[2][13]/Q -type DFF DFF
add mapped point STAGE3/d_re[2][15]/q STAGE3/d_re_reg[2][15]/Q -type DFF DFF
add mapped point STAGE3/d_re[3][0]/q STAGE3/d_re_reg[3][0]/Q -type DFF DFF
add mapped point STAGE3/d_re[3][1]/q STAGE3/d_re_reg[3][1]/Q -type DFF DFF
add mapped point STAGE3/d_re[3][2]/q STAGE3/d_re_reg[3][2]/Q -type DFF DFF
add mapped point STAGE3/d_re[3][3]/q STAGE3/d_re_reg[3][3]/Q -type DFF DFF
add mapped point STAGE3/d_re[3][4]/q STAGE3/d_re_reg[3][4]/Q -type DFF DFF
add mapped point STAGE3/d_re[3][5]/q STAGE3/d_re_reg[3][5]/Q -type DFF DFF
add mapped point STAGE3/d_re[3][6]/q STAGE3/d_re_reg[3][6]/Q -type DFF DFF
add mapped point STAGE3/d_re[3][7]/q STAGE3/d_re_reg[3][7]/Q -type DFF DFF
add mapped point STAGE3/d_re[3][8]/q STAGE3/d_re_reg[3][8]/Q -type DFF DFF
add mapped point STAGE3/d_re[3][9]/q STAGE3/d_re_reg[3][9]/Q -type DFF DFF
add mapped point STAGE3/d_re[3][10]/q STAGE3/d_re_reg[3][10]/Q -type DFF DFF
add mapped point STAGE3/d_re[3][11]/q STAGE3/d_re_reg[3][11]/Q -type DFF DFF
add mapped point STAGE3/d_re[3][12]/q STAGE3/d_re_reg[3][12]/Q -type DFF DFF
add mapped point STAGE3/d_re[3][13]/q STAGE3/d_re_reg[3][13]/Q -type DFF DFF
add mapped point STAGE3/d_re[3][14]/q STAGE3/d_re_reg[3][14]/Q -type DFF DFF
add mapped point STAGE3/d_re[3][15]/q STAGE3/d_re_reg[3][15]/Q -type DFF DFF
add mapped point STAGE3/sum_im[0][2]/q STAGE3/sum_im_reg[0][2]/Q -type DFF DFF
add mapped point STAGE3/sum_im[0][3]/q STAGE3/sum_im_reg[0][3]/Q -type DFF DFF
add mapped point STAGE3/sum_im[0][4]/q STAGE3/sum_im_reg[0][4]/Q -type DFF DFF
add mapped point STAGE3/sum_im[0][5]/q STAGE3/sum_im_reg[0][5]/Q -type DFF DFF
add mapped point STAGE3/sum_im[0][6]/q STAGE3/sum_im_reg[0][6]/Q -type DFF DFF
add mapped point STAGE3/sum_im[0][7]/q STAGE3/sum_im_reg[0][7]/Q -type DFF DFF
add mapped point STAGE3/sum_im[0][8]/q STAGE3/sum_im_reg[0][8]/Q -type DFF DFF
add mapped point STAGE3/sum_im[0][9]/q STAGE3/sum_im_reg[0][9]/Q -type DFF DFF
add mapped point STAGE3/sum_im[0][10]/q STAGE3/sum_im_reg[0][10]/Q -type DFF DFF
add mapped point STAGE3/sum_im[0][11]/q STAGE3/sum_im_reg[0][11]/Q -type DFF DFF
add mapped point STAGE3/sum_im[0][12]/q STAGE3/sum_im_reg[0][12]/Q -type DFF DFF
add mapped point STAGE3/sum_im[0][13]/q STAGE3/sum_im_reg[0][13]/Q -type DFF DFF
add mapped point STAGE3/sum_im[0][14]/q STAGE3/sum_im_reg[0][14]/Q -type DFF DFF
add mapped point STAGE3/sum_im[0][15]/q STAGE3/sum_im_reg[0][15]/Q -type DFF DFF
add mapped point STAGE3/sum_im[1][1]/q STAGE3/sum_im_reg[1][1]/Q -type DFF DFF
add mapped point STAGE3/sum_im[1][2]/q STAGE3/sum_im_reg[1][2]/Q -type DFF DFF
add mapped point STAGE3/sum_im[2][0]/q STAGE3/sum_im_reg[2][0]/Q -type DFF DFF
add mapped point STAGE3/sum_im[2][2]/q STAGE3/sum_im_reg[2][2]/Q -type DFF DFF
add mapped point STAGE3/sum_im[3][0]/q STAGE3/sum_im_reg[3][0]/Q -type DFF DFF
add mapped point STAGE3/sum_im[3][2]/q STAGE3/sum_im_reg[3][2]/Q -type DFF DFF
add mapped point STAGE3/sum_im[3][3]/q STAGE3/sum_im_reg[3][3]/Q -type DFF DFF
add mapped point STAGE3/sum_im[3][4]/q STAGE3/sum_im_reg[3][4]/Q -type DFF DFF
add mapped point STAGE3/sum_im[3][5]/q STAGE3/sum_im_reg[3][5]/Q -type DFF DFF
add mapped point STAGE3/sum_im[3][6]/q STAGE3/sum_im_reg[3][6]/Q -type DFF DFF
add mapped point STAGE3/sum_im[3][7]/q STAGE3/sum_im_reg[3][7]/Q -type DFF DFF
add mapped point STAGE3/sum_im[3][8]/q STAGE3/sum_im_reg[3][8]/Q -type DFF DFF
add mapped point STAGE3/sum_im[3][9]/q STAGE3/sum_im_reg[3][9]/Q -type DFF DFF
add mapped point STAGE3/sum_im[3][10]/q STAGE3/sum_im_reg[3][10]/Q -type DFF DFF
add mapped point STAGE3/sum_im[3][11]/q STAGE3/sum_im_reg[3][11]/Q -type DFF DFF
add mapped point STAGE3/sum_im[3][12]/q STAGE3/sum_im_reg[3][12]/Q -type DFF DFF
add mapped point STAGE3/sum_im[3][13]/q STAGE3/sum_im_reg[3][13]/Q -type DFF DFF
add mapped point STAGE3/sum_im[3][14]/q STAGE3/sum_im_reg[3][14]/Q -type DFF DFF
add mapped point STAGE3/sum_im[3][15]/q STAGE3/sum_im_reg[3][15]/Q -type DFF DFF
add mapped point STAGE3/sum_re[0][0]/q STAGE3/sum_re_reg[0][0]/Q -type DFF DFF
add mapped point STAGE3/sum_re[0][1]/q STAGE3/sum_re_reg[0][1]/Q -type DFF DFF
add mapped point STAGE3/sum_re[0][2]/q STAGE3/sum_re_reg[0][2]/Q -type DFF DFF
add mapped point STAGE3/sum_re[0][3]/q STAGE3/sum_re_reg[0][3]/Q -type DFF DFF
add mapped point STAGE3/sum_re[0][4]/q STAGE3/sum_re_reg[0][4]/Q -type DFF DFF
add mapped point STAGE3/sum_re[0][5]/q STAGE3/sum_re_reg[0][5]/Q -type DFF DFF
add mapped point STAGE3/sum_re[0][6]/q STAGE3/sum_re_reg[0][6]/Q -type DFF DFF
add mapped point STAGE3/sum_re[0][7]/q STAGE3/sum_re_reg[0][7]/Q -type DFF DFF
add mapped point STAGE3/sum_re[0][8]/q STAGE3/sum_re_reg[0][8]/Q -type DFF DFF
add mapped point STAGE3/sum_re[0][9]/q STAGE3/sum_re_reg[0][9]/Q -type DFF DFF
add mapped point STAGE3/sum_re[0][10]/q STAGE3/sum_re_reg[0][10]/Q -type DFF DFF
add mapped point STAGE3/sum_re[0][11]/q STAGE3/sum_re_reg[0][11]/Q -type DFF DFF
add mapped point STAGE3/sum_re[0][12]/q STAGE3/sum_re_reg[0][12]/Q -type DFF DFF
add mapped point STAGE3/sum_re[0][13]/q STAGE3/sum_re_reg[0][13]/Q -type DFF DFF
add mapped point STAGE3/sum_re[0][14]/q STAGE3/sum_re_reg[0][14]/Q -type DFF DFF
add mapped point STAGE3/sum_re[0][15]/q STAGE3/sum_re_reg[0][15]/Q -type DFF DFF
add mapped point STAGE3/sum_re[3][0]/q STAGE3/sum_re_reg[3][0]/Q -type DFF DFF
add mapped point STAGE3/sum_re[3][1]/q STAGE3/sum_re_reg[3][1]/Q -type DFF DFF
add mapped point STAGE3/sum_re[3][2]/q STAGE3/sum_re_reg[3][2]/Q -type DFF DFF
add mapped point STAGE3/sum_re[3][3]/q STAGE3/sum_re_reg[3][3]/Q -type DFF DFF
add mapped point STAGE3/sum_re[3][4]/q STAGE3/sum_re_reg[3][4]/Q -type DFF DFF
add mapped point STAGE3/sum_re[3][5]/q STAGE3/sum_re_reg[3][5]/Q -type DFF DFF
add mapped point STAGE3/sum_re[3][6]/q STAGE3/sum_re_reg[3][6]/Q -type DFF DFF
add mapped point STAGE3/sum_re[3][7]/q STAGE3/sum_re_reg[3][7]/Q -type DFF DFF
add mapped point STAGE3/sum_re[3][8]/q STAGE3/sum_re_reg[3][8]/Q -type DFF DFF
add mapped point STAGE3/sum_re[3][9]/q STAGE3/sum_re_reg[3][9]/Q -type DFF DFF
add mapped point STAGE3/sum_re[3][10]/q STAGE3/sum_re_reg[3][10]/Q -type DFF DFF
add mapped point STAGE3/sum_re[3][11]/q STAGE3/sum_re_reg[3][11]/Q -type DFF DFF
add mapped point STAGE3/sum_re[3][12]/q STAGE3/sum_re_reg[3][12]/Q -type DFF DFF
add mapped point STAGE3/sum_re[3][13]/q STAGE3/sum_re_reg[3][13]/Q -type DFF DFF
add mapped point STAGE3/sum_re[3][14]/q STAGE3/sum_re_reg[3][14]/Q -type DFF DFF
add mapped point STAGE3/sum_re[3][15]/q STAGE3/sum_re_reg[3][15]/Q -type DFF DFF
add mapped point STAGE3/xout_im[0]/q STAGE3/xout_im_reg[0]/Q -type DFF DFF
add mapped point STAGE3/xout_im[1]/q STAGE3/xout_im_reg[1]/Q -type DFF DFF
add mapped point STAGE3/xout_im[2]/q STAGE3/xout_im_reg[2]/Q -type DFF DFF
add mapped point STAGE3/xout_im[3]/q STAGE3/xout_im_reg[3]/Q -type DFF DFF
add mapped point STAGE3/xout_im[4]/q STAGE3/xout_im_reg[4]/Q -type DFF DFF
add mapped point STAGE3/xout_im[5]/q STAGE3/xout_im_reg[5]/Q -type DFF DFF
add mapped point STAGE3/xout_im[6]/q STAGE3/xout_im_reg[6]/Q -type DFF DFF
add mapped point STAGE3/xout_im[7]/q STAGE3/xout_im_reg[7]/Q -type DFF DFF
add mapped point STAGE3/xout_im[8]/q STAGE3/xout_im_reg[8]/Q -type DFF DFF
add mapped point STAGE3/xout_im[9]/q STAGE3/xout_im_reg[9]/Q -type DFF DFF
add mapped point STAGE3/xout_im[10]/q STAGE3/xout_im_reg[10]/Q -type DFF DFF
add mapped point STAGE3/xout_im[11]/q STAGE3/xout_im_reg[11]/Q -type DFF DFF
add mapped point STAGE3/xout_im[12]/q STAGE3/xout_im_reg[12]/Q -type DFF DFF
add mapped point STAGE3/xout_im[13]/q STAGE3/xout_im_reg[13]/Q -type DFF DFF
add mapped point STAGE3/xout_im[14]/q STAGE3/xout_im_reg[14]/Q -type DFF DFF
add mapped point STAGE3/xout_im[15]/q STAGE3/xout_im_reg[15]/Q -type DFF DFF
add mapped point STAGE3/xout_re[0]/q STAGE3/xout_re_reg[0]/Q -type DFF DFF
add mapped point STAGE3/xout_re[1]/q STAGE3/xout_re_reg[1]/Q -type DFF DFF
add mapped point STAGE3/xout_re[2]/q STAGE3/xout_re_reg[2]/Q -type DFF DFF
add mapped point STAGE3/xout_re[3]/q STAGE3/xout_re_reg[3]/Q -type DFF DFF
add mapped point STAGE3/xout_re[4]/q STAGE3/xout_re_reg[4]/Q -type DFF DFF
add mapped point STAGE3/xout_re[5]/q STAGE3/xout_re_reg[5]/Q -type DFF DFF
add mapped point STAGE3/xout_re[6]/q STAGE3/xout_re_reg[6]/Q -type DFF DFF
add mapped point STAGE3/xout_re[7]/q STAGE3/xout_re_reg[7]/Q -type DFF DFF
add mapped point STAGE3/xout_re[8]/q STAGE3/xout_re_reg[8]/Q -type DFF DFF
add mapped point STAGE3/xout_re[9]/q STAGE3/xout_re_reg[9]/Q -type DFF DFF
add mapped point STAGE3/xout_re[10]/q STAGE3/xout_re_reg[10]/Q -type DFF DFF
add mapped point STAGE3/xout_re[11]/q STAGE3/xout_re_reg[11]/Q -type DFF DFF
add mapped point STAGE3/xout_re[12]/q STAGE3/xout_re_reg[12]/Q -type DFF DFF
add mapped point STAGE3/xout_re[13]/q STAGE3/xout_re_reg[13]/Q -type DFF DFF
add mapped point STAGE3/xout_re[14]/q STAGE3/xout_re_reg[14]/Q -type DFF DFF
add mapped point STAGE3/xout_re[15]/q STAGE3/xout_re_reg[15]/Q -type DFF DFF
add mapped point STAGE3/cnt[1]/q STAGE3/cnt_reg[1]/Q -type DFF DFF
add mapped point STAGE3/cnt[2]/q STAGE3/cnt_reg[2]/Q -type DFF DFF
add mapped point STAGE3/d_im[0][1]/q STAGE3/d_im_reg[0][1]/Q -type DFF DFF
add mapped point STAGE3/d_im[0][2]/q STAGE3/d_im_reg[0][2]/Q -type DFF DFF
add mapped point STAGE3/d_im[2][3]/q STAGE3/d_im_reg[2][3]/Q -type DFF DFF
add mapped point STAGE3/d_im[2][9]/q STAGE3/d_im_reg[2][9]/Q -type DFF DFF
add mapped point STAGE3/d_im[2][10]/q STAGE3/d_im_reg[2][10]/Q -type DFF DFF
add mapped point STAGE3/d_im[2][11]/q STAGE3/d_im_reg[2][11]/Q -type DFF DFF
add mapped point STAGE3/d_im[2][12]/q STAGE3/d_im_reg[2][12]/Q -type DFF DFF
add mapped point STAGE3/d_im[2][13]/q STAGE3/d_im_reg[2][13]/Q -type DFF DFF
add mapped point STAGE3/d_im[2][14]/q STAGE3/d_im_reg[2][14]/Q -type DFF DFF
add mapped point STAGE3/d_im[2][15]/q STAGE3/d_im_reg[2][15]/Q -type DFF DFF
add mapped point STAGE3/d_re[2][0]/q STAGE3/d_re_reg[2][0]/Q -type DFF DFF
add mapped point STAGE3/d_re[2][1]/q STAGE3/d_re_reg[2][1]/Q -type DFF DFF
add mapped point STAGE3/d_re[2][2]/q STAGE3/d_re_reg[2][2]/Q -type DFF DFF
add mapped point STAGE3/d_re[2][3]/q STAGE3/d_re_reg[2][3]/Q -type DFF DFF
add mapped point STAGE3/d_re[2][4]/q STAGE3/d_re_reg[2][4]/Q -type DFF DFF
add mapped point STAGE3/d_re[2][6]/q STAGE3/d_re_reg[2][6]/Q -type DFF DFF
add mapped point STAGE3/d_re[2][8]/q STAGE3/d_re_reg[2][8]/Q -type DFF DFF
add mapped point STAGE3/d_re[2][10]/q STAGE3/d_re_reg[2][10]/Q -type DFF DFF
add mapped point STAGE3/d_re[2][12]/q STAGE3/d_re_reg[2][12]/Q -type DFF DFF
add mapped point STAGE3/d_re[2][14]/q STAGE3/d_re_reg[2][14]/Q -type DFF DFF
add mapped point STAGE3/phase/q STAGE3/phase_reg/Q -type DFF DFF
add mapped point STAGE3/sum_im[0][0]/q STAGE3/sum_im_reg[0][0]/Q -type DFF DFF
add mapped point STAGE3/sum_im[0][1]/q STAGE3/sum_im_reg[0][1]/Q -type DFF DFF
add mapped point STAGE3/sum_im[1][0]/q STAGE3/sum_im_reg[1][0]/Q -type DFF DFF
add mapped point STAGE3/sum_im[1][3]/q STAGE3/sum_im_reg[1][3]/Q -type DFF DFF
add mapped point STAGE3/sum_im[1][4]/q STAGE3/sum_im_reg[1][4]/Q -type DFF DFF
add mapped point STAGE3/sum_im[1][5]/q STAGE3/sum_im_reg[1][5]/Q -type DFF DFF
add mapped point STAGE3/sum_im[1][6]/q STAGE3/sum_im_reg[1][6]/Q -type DFF DFF
add mapped point STAGE3/sum_im[1][7]/q STAGE3/sum_im_reg[1][7]/Q -type DFF DFF
add mapped point STAGE3/sum_im[1][8]/q STAGE3/sum_im_reg[1][8]/Q -type DFF DFF
add mapped point STAGE3/sum_im[1][9]/q STAGE3/sum_im_reg[1][9]/Q -type DFF DFF
add mapped point STAGE3/sum_im[1][10]/q STAGE3/sum_im_reg[1][10]/Q -type DFF DFF
add mapped point STAGE3/sum_im[1][11]/q STAGE3/sum_im_reg[1][11]/Q -type DFF DFF
add mapped point STAGE3/sum_im[1][12]/q STAGE3/sum_im_reg[1][12]/Q -type DFF DFF
add mapped point STAGE3/sum_im[1][13]/q STAGE3/sum_im_reg[1][13]/Q -type DFF DFF
add mapped point STAGE3/sum_im[1][14]/q STAGE3/sum_im_reg[1][14]/Q -type DFF DFF
add mapped point STAGE3/sum_im[1][15]/q STAGE3/sum_im_reg[1][15]/Q -type DFF DFF
add mapped point STAGE3/sum_im[2][1]/q STAGE3/sum_im_reg[2][1]/Q -type DFF DFF
add mapped point STAGE3/sum_im[2][3]/q STAGE3/sum_im_reg[2][3]/Q -type DFF DFF
add mapped point STAGE3/sum_im[2][4]/q STAGE3/sum_im_reg[2][4]/Q -type DFF DFF
add mapped point STAGE3/sum_im[2][5]/q STAGE3/sum_im_reg[2][5]/Q -type DFF DFF
add mapped point STAGE3/sum_im[2][6]/q STAGE3/sum_im_reg[2][6]/Q -type DFF DFF
add mapped point STAGE3/sum_im[2][7]/q STAGE3/sum_im_reg[2][7]/Q -type DFF DFF
add mapped point STAGE3/sum_im[2][8]/q STAGE3/sum_im_reg[2][8]/Q -type DFF DFF
add mapped point STAGE3/sum_im[2][9]/q STAGE3/sum_im_reg[2][9]/Q -type DFF DFF
add mapped point STAGE3/sum_im[2][10]/q STAGE3/sum_im_reg[2][10]/Q -type DFF DFF
add mapped point STAGE3/sum_im[2][11]/q STAGE3/sum_im_reg[2][11]/Q -type DFF DFF
add mapped point STAGE3/sum_im[2][12]/q STAGE3/sum_im_reg[2][12]/Q -type DFF DFF
add mapped point STAGE3/sum_im[2][13]/q STAGE3/sum_im_reg[2][13]/Q -type DFF DFF
add mapped point STAGE3/sum_im[2][14]/q STAGE3/sum_im_reg[2][14]/Q -type DFF DFF
add mapped point STAGE3/sum_im[2][15]/q STAGE3/sum_im_reg[2][15]/Q -type DFF DFF
add mapped point STAGE3/sum_im[3][1]/q STAGE3/sum_im_reg[3][1]/Q -type DFF DFF
add mapped point STAGE3/sum_re[1][0]/q STAGE3/sum_re_reg[1][0]/Q -type DFF DFF
add mapped point STAGE3/sum_re[1][1]/q STAGE3/sum_re_reg[1][1]/Q -type DFF DFF
add mapped point STAGE3/sum_re[1][2]/q STAGE3/sum_re_reg[1][2]/Q -type DFF DFF
add mapped point STAGE3/sum_re[1][3]/q STAGE3/sum_re_reg[1][3]/Q -type DFF DFF
add mapped point STAGE3/sum_re[1][4]/q STAGE3/sum_re_reg[1][4]/Q -type DFF DFF
add mapped point STAGE3/sum_re[1][5]/q STAGE3/sum_re_reg[1][5]/Q -type DFF DFF
add mapped point STAGE3/sum_re[1][6]/q STAGE3/sum_re_reg[1][6]/Q -type DFF DFF
add mapped point STAGE3/sum_re[1][7]/q STAGE3/sum_re_reg[1][7]/Q -type DFF DFF
add mapped point STAGE3/sum_re[1][8]/q STAGE3/sum_re_reg[1][8]/Q -type DFF DFF
add mapped point STAGE3/sum_re[1][9]/q STAGE3/sum_re_reg[1][9]/Q -type DFF DFF
add mapped point STAGE3/sum_re[1][10]/q STAGE3/sum_re_reg[1][10]/Q -type DFF DFF
add mapped point STAGE3/sum_re[1][11]/q STAGE3/sum_re_reg[1][11]/Q -type DFF DFF
add mapped point STAGE3/sum_re[1][12]/q STAGE3/sum_re_reg[1][12]/Q -type DFF DFF
add mapped point STAGE3/sum_re[1][13]/q STAGE3/sum_re_reg[1][13]/Q -type DFF DFF
add mapped point STAGE3/sum_re[1][14]/q STAGE3/sum_re_reg[1][14]/Q -type DFF DFF
add mapped point STAGE3/sum_re[1][15]/q STAGE3/sum_re_reg[1][15]/Q -type DFF DFF
add mapped point STAGE3/sum_re[2][0]/q STAGE3/sum_re_reg[2][0]/Q -type DFF DFF
add mapped point STAGE3/sum_re[2][1]/q STAGE3/sum_re_reg[2][1]/Q -type DFF DFF
add mapped point STAGE3/sum_re[2][2]/q STAGE3/sum_re_reg[2][2]/Q -type DFF DFF
add mapped point STAGE3/sum_re[2][3]/q STAGE3/sum_re_reg[2][3]/Q -type DFF DFF
add mapped point STAGE3/sum_re[2][4]/q STAGE3/sum_re_reg[2][4]/Q -type DFF DFF
add mapped point STAGE3/sum_re[2][5]/q STAGE3/sum_re_reg[2][5]/Q -type DFF DFF
add mapped point STAGE3/sum_re[2][6]/q STAGE3/sum_re_reg[2][6]/Q -type DFF DFF
add mapped point STAGE3/sum_re[2][7]/q STAGE3/sum_re_reg[2][7]/Q -type DFF DFF
add mapped point STAGE3/sum_re[2][8]/q STAGE3/sum_re_reg[2][8]/Q -type DFF DFF
add mapped point STAGE3/sum_re[2][9]/q STAGE3/sum_re_reg[2][9]/Q -type DFF DFF
add mapped point STAGE3/sum_re[2][10]/q STAGE3/sum_re_reg[2][10]/Q -type DFF DFF
add mapped point STAGE3/sum_re[2][11]/q STAGE3/sum_re_reg[2][11]/Q -type DFF DFF
add mapped point STAGE3/sum_re[2][12]/q STAGE3/sum_re_reg[2][12]/Q -type DFF DFF
add mapped point STAGE3/sum_re[2][13]/q STAGE3/sum_re_reg[2][13]/Q -type DFF DFF
add mapped point STAGE3/sum_re[2][14]/q STAGE3/sum_re_reg[2][14]/Q -type DFF DFF
add mapped point STAGE3/sum_re[2][15]/q STAGE3/sum_re_reg[2][15]/Q -type DFF DFF
add mapped point STAGE1/valid_out/q STAGE1_valid_out_reg/Q -type DFF DFF
add mapped point STAGE1/cnt[2]/q STAGE1_cnt_reg[2]/Q -type DFF DFF
add mapped point STAGE1/d_im[0][0]/q STAGE1_d_im_reg[0][0]/Q -type DFF DFF
add mapped point STAGE1/d_im[0][1]/q STAGE1_d_im_reg[0][1]/Q -type DFF DFF
add mapped point STAGE1/d_im[0][2]/q STAGE1_d_im_reg[0][2]/Q -type DFF DFF
add mapped point STAGE1/d_im[0][3]/q STAGE1_d_im_reg[0][3]/Q -type DFF DFF
add mapped point STAGE1/d_im[0][4]/q STAGE1_d_im_reg[0][4]/Q -type DFF DFF
add mapped point STAGE1/d_im[0][5]/q STAGE1_d_im_reg[0][5]/Q -type DFF DFF
add mapped point STAGE1/d_im[0][6]/q STAGE1_d_im_reg[0][6]/Q -type DFF DFF
add mapped point STAGE1/d_im[0][7]/q STAGE1_d_im_reg[0][7]/Q -type DFF DFF
add mapped point STAGE1/d_im[0][8]/q STAGE1_d_im_reg[0][8]/Q -type DFF DFF
add mapped point STAGE1/d_im[0][9]/q STAGE1_d_im_reg[0][9]/Q -type DFF DFF
add mapped point STAGE1/d_im[0][10]/q STAGE1_d_im_reg[0][10]/Q -type DFF DFF
add mapped point STAGE1/d_im[0][11]/q STAGE1_d_im_reg[0][11]/Q -type DFF DFF
add mapped point STAGE1/d_im[0][12]/q STAGE1_d_im_reg[0][12]/Q -type DFF DFF
add mapped point STAGE1/d_im[0][13]/q STAGE1_d_im_reg[0][13]/Q -type DFF DFF
add mapped point STAGE1/d_im[0][14]/q STAGE1_d_im_reg[0][14]/Q -type DFF DFF
add mapped point STAGE1/d_im[0][15]/q STAGE1_d_im_reg[0][15]/Q -type DFF DFF
add mapped point STAGE1/d_im[1][0]/q STAGE1_d_im_reg[1][0]/Q -type DFF DFF
add mapped point STAGE1/d_im[1][1]/q STAGE1_d_im_reg[1][1]/Q -type DFF DFF
add mapped point STAGE1/d_im[1][2]/q STAGE1_d_im_reg[1][2]/Q -type DFF DFF
add mapped point STAGE1/d_im[1][3]/q STAGE1_d_im_reg[1][3]/Q -type DFF DFF
add mapped point STAGE1/d_im[1][4]/q STAGE1_d_im_reg[1][4]/Q -type DFF DFF
add mapped point STAGE1/d_im[1][5]/q STAGE1_d_im_reg[1][5]/Q -type DFF DFF
add mapped point STAGE1/d_im[1][6]/q STAGE1_d_im_reg[1][6]/Q -type DFF DFF
add mapped point STAGE1/d_im[1][7]/q STAGE1_d_im_reg[1][7]/Q -type DFF DFF
add mapped point STAGE1/d_im[1][8]/q STAGE1_d_im_reg[1][8]/Q -type DFF DFF
add mapped point STAGE1/d_im[1][9]/q STAGE1_d_im_reg[1][9]/Q -type DFF DFF
add mapped point STAGE1/d_im[1][10]/q STAGE1_d_im_reg[1][10]/Q -type DFF DFF
add mapped point STAGE1/d_im[1][11]/q STAGE1_d_im_reg[1][11]/Q -type DFF DFF
add mapped point STAGE1/d_im[1][12]/q STAGE1_d_im_reg[1][12]/Q -type DFF DFF
add mapped point STAGE1/d_im[1][13]/q STAGE1_d_im_reg[1][13]/Q -type DFF DFF
add mapped point STAGE1/d_im[1][14]/q STAGE1_d_im_reg[1][14]/Q -type DFF DFF
add mapped point STAGE1/d_im[1][15]/q STAGE1_d_im_reg[1][15]/Q -type DFF DFF
add mapped point STAGE1/d_im[2][0]/q STAGE1_d_im_reg[2][0]/Q -type DFF DFF
add mapped point STAGE1/d_im[2][1]/q STAGE1_d_im_reg[2][1]/Q -type DFF DFF
add mapped point STAGE1/d_im[2][2]/q STAGE1_d_im_reg[2][2]/Q -type DFF DFF
add mapped point STAGE1/d_im[2][3]/q STAGE1_d_im_reg[2][3]/Q -type DFF DFF
add mapped point STAGE1/d_im[2][4]/q STAGE1_d_im_reg[2][4]/Q -type DFF DFF
add mapped point STAGE1/d_im[2][5]/q STAGE1_d_im_reg[2][5]/Q -type DFF DFF
add mapped point STAGE1/d_im[2][6]/q STAGE1_d_im_reg[2][6]/Q -type DFF DFF
add mapped point STAGE1/d_im[2][7]/q STAGE1_d_im_reg[2][7]/Q -type DFF DFF
add mapped point STAGE1/d_im[2][8]/q STAGE1_d_im_reg[2][8]/Q -type DFF DFF
add mapped point STAGE1/d_im[2][9]/q STAGE1_d_im_reg[2][9]/Q -type DFF DFF
add mapped point STAGE1/d_im[2][10]/q STAGE1_d_im_reg[2][10]/Q -type DFF DFF
add mapped point STAGE1/d_im[2][11]/q STAGE1_d_im_reg[2][11]/Q -type DFF DFF
add mapped point STAGE1/d_im[2][12]/q STAGE1_d_im_reg[2][12]/Q -type DFF DFF
add mapped point STAGE1/d_im[2][13]/q STAGE1_d_im_reg[2][13]/Q -type DFF DFF
add mapped point STAGE1/d_im[2][14]/q STAGE1_d_im_reg[2][14]/Q -type DFF DFF
add mapped point STAGE1/d_im[2][15]/q STAGE1_d_im_reg[2][15]/Q -type DFF DFF
add mapped point STAGE1/d_im[3][0]/q STAGE1_d_im_reg[3][0]/Q -type DFF DFF
add mapped point STAGE1/d_im[3][1]/q STAGE1_d_im_reg[3][1]/Q -type DFF DFF
add mapped point STAGE1/d_im[3][2]/q STAGE1_d_im_reg[3][2]/Q -type DFF DFF
add mapped point STAGE1/d_im[3][3]/q STAGE1_d_im_reg[3][3]/Q -type DFF DFF
add mapped point STAGE1/d_im[3][4]/q STAGE1_d_im_reg[3][4]/Q -type DFF DFF
add mapped point STAGE1/d_im[3][5]/q STAGE1_d_im_reg[3][5]/Q -type DFF DFF
add mapped point STAGE1/d_im[3][6]/q STAGE1_d_im_reg[3][6]/Q -type DFF DFF
add mapped point STAGE1/d_im[3][7]/q STAGE1_d_im_reg[3][7]/Q -type DFF DFF
add mapped point STAGE1/d_im[3][8]/q STAGE1_d_im_reg[3][8]/Q -type DFF DFF
add mapped point STAGE1/d_im[3][9]/q STAGE1_d_im_reg[3][9]/Q -type DFF DFF
add mapped point STAGE1/d_im[3][10]/q STAGE1_d_im_reg[3][10]/Q -type DFF DFF
add mapped point STAGE1/d_im[3][11]/q STAGE1_d_im_reg[3][11]/Q -type DFF DFF
add mapped point STAGE1/d_im[3][12]/q STAGE1_d_im_reg[3][12]/Q -type DFF DFF
add mapped point STAGE1/d_im[3][13]/q STAGE1_d_im_reg[3][13]/Q -type DFF DFF
add mapped point STAGE1/d_im[3][14]/q STAGE1_d_im_reg[3][14]/Q -type DFF DFF
add mapped point STAGE1/d_im[3][15]/q STAGE1_d_im_reg[3][15]/Q -type DFF DFF
add mapped point STAGE1/d_re[0][0]/q STAGE1_d_re_reg[0][0]/Q -type DFF DFF
add mapped point STAGE1/d_re[0][1]/q STAGE1_d_re_reg[0][1]/Q -type DFF DFF
add mapped point STAGE1/d_re[0][2]/q STAGE1_d_re_reg[0][2]/Q -type DFF DFF
add mapped point STAGE1/d_re[0][3]/q STAGE1_d_re_reg[0][3]/Q -type DFF DFF
add mapped point STAGE1/d_re[0][4]/q STAGE1_d_re_reg[0][4]/Q -type DFF DFF
add mapped point STAGE1/d_re[0][5]/q STAGE1_d_re_reg[0][5]/Q -type DFF DFF
add mapped point STAGE1/d_re[0][6]/q STAGE1_d_re_reg[0][6]/Q -type DFF DFF
add mapped point STAGE1/d_re[0][7]/q STAGE1_d_re_reg[0][7]/Q -type DFF DFF
add mapped point STAGE1/d_re[0][8]/q STAGE1_d_re_reg[0][8]/Q -type DFF DFF
add mapped point STAGE1/d_re[0][9]/q STAGE1_d_re_reg[0][9]/Q -type DFF DFF
add mapped point STAGE1/d_re[0][10]/q STAGE1_d_re_reg[0][10]/Q -type DFF DFF
add mapped point STAGE1/d_re[0][11]/q STAGE1_d_re_reg[0][11]/Q -type DFF DFF
add mapped point STAGE1/d_re[0][12]/q STAGE1_d_re_reg[0][12]/Q -type DFF DFF
add mapped point STAGE1/d_re[0][13]/q STAGE1_d_re_reg[0][13]/Q -type DFF DFF
add mapped point STAGE1/d_re[0][14]/q STAGE1_d_re_reg[0][14]/Q -type DFF DFF
add mapped point STAGE1/d_re[0][15]/q STAGE1_d_re_reg[0][15]/Q -type DFF DFF
add mapped point STAGE1/d_re[1][0]/q STAGE1_d_re_reg[1][0]/Q -type DFF DFF
add mapped point STAGE1/d_re[1][1]/q STAGE1_d_re_reg[1][1]/Q -type DFF DFF
add mapped point STAGE1/d_re[1][2]/q STAGE1_d_re_reg[1][2]/Q -type DFF DFF
add mapped point STAGE1/d_re[1][3]/q STAGE1_d_re_reg[1][3]/Q -type DFF DFF
add mapped point STAGE1/d_re[1][4]/q STAGE1_d_re_reg[1][4]/Q -type DFF DFF
add mapped point STAGE1/d_re[1][5]/q STAGE1_d_re_reg[1][5]/Q -type DFF DFF
add mapped point STAGE1/d_re[1][6]/q STAGE1_d_re_reg[1][6]/Q -type DFF DFF
add mapped point STAGE1/d_re[1][7]/q STAGE1_d_re_reg[1][7]/Q -type DFF DFF
add mapped point STAGE1/d_re[1][8]/q STAGE1_d_re_reg[1][8]/Q -type DFF DFF
add mapped point STAGE1/d_re[1][9]/q STAGE1_d_re_reg[1][9]/Q -type DFF DFF
add mapped point STAGE1/d_re[1][10]/q STAGE1_d_re_reg[1][10]/Q -type DFF DFF
add mapped point STAGE1/d_re[1][11]/q STAGE1_d_re_reg[1][11]/Q -type DFF DFF
add mapped point STAGE1/d_re[1][12]/q STAGE1_d_re_reg[1][12]/Q -type DFF DFF
add mapped point STAGE1/d_re[1][13]/q STAGE1_d_re_reg[1][13]/Q -type DFF DFF
add mapped point STAGE1/d_re[1][14]/q STAGE1_d_re_reg[1][14]/Q -type DFF DFF
add mapped point STAGE1/d_re[1][15]/q STAGE1_d_re_reg[1][15]/Q -type DFF DFF
add mapped point STAGE1/d_re[2][0]/q STAGE1_d_re_reg[2][0]/Q -type DFF DFF
add mapped point STAGE1/d_re[2][1]/q STAGE1_d_re_reg[2][1]/Q -type DFF DFF
add mapped point STAGE1/d_re[2][2]/q STAGE1_d_re_reg[2][2]/Q -type DFF DFF
add mapped point STAGE1/d_re[2][3]/q STAGE1_d_re_reg[2][3]/Q -type DFF DFF
add mapped point STAGE1/d_re[2][4]/q STAGE1_d_re_reg[2][4]/Q -type DFF DFF
add mapped point STAGE1/d_re[2][5]/q STAGE1_d_re_reg[2][5]/Q -type DFF DFF
add mapped point STAGE1/d_re[2][6]/q STAGE1_d_re_reg[2][6]/Q -type DFF DFF
add mapped point STAGE1/d_re[2][7]/q STAGE1_d_re_reg[2][7]/Q -type DFF DFF
add mapped point STAGE1/d_re[2][8]/q STAGE1_d_re_reg[2][8]/Q -type DFF DFF
add mapped point STAGE1/d_re[2][9]/q STAGE1_d_re_reg[2][9]/Q -type DFF DFF
add mapped point STAGE1/d_re[2][10]/q STAGE1_d_re_reg[2][10]/Q -type DFF DFF
add mapped point STAGE1/d_re[2][11]/q STAGE1_d_re_reg[2][11]/Q -type DFF DFF
add mapped point STAGE1/d_re[2][12]/q STAGE1_d_re_reg[2][12]/Q -type DFF DFF
add mapped point STAGE1/d_re[2][13]/q STAGE1_d_re_reg[2][13]/Q -type DFF DFF
add mapped point STAGE1/d_re[2][14]/q STAGE1_d_re_reg[2][14]/Q -type DFF DFF
add mapped point STAGE1/d_re[2][15]/q STAGE1_d_re_reg[2][15]/Q -type DFF DFF
add mapped point STAGE1/d_re[3][0]/q STAGE1_d_re_reg[3][0]/Q -type DFF DFF
add mapped point STAGE1/d_re[3][1]/q STAGE1_d_re_reg[3][1]/Q -type DFF DFF
add mapped point STAGE1/d_re[3][2]/q STAGE1_d_re_reg[3][2]/Q -type DFF DFF
add mapped point STAGE1/d_re[3][3]/q STAGE1_d_re_reg[3][3]/Q -type DFF DFF
add mapped point STAGE1/d_re[3][4]/q STAGE1_d_re_reg[3][4]/Q -type DFF DFF
add mapped point STAGE1/d_re[3][5]/q STAGE1_d_re_reg[3][5]/Q -type DFF DFF
add mapped point STAGE1/d_re[3][6]/q STAGE1_d_re_reg[3][6]/Q -type DFF DFF
add mapped point STAGE1/d_re[3][7]/q STAGE1_d_re_reg[3][7]/Q -type DFF DFF
add mapped point STAGE1/d_re[3][8]/q STAGE1_d_re_reg[3][8]/Q -type DFF DFF
add mapped point STAGE1/d_re[3][9]/q STAGE1_d_re_reg[3][9]/Q -type DFF DFF
add mapped point STAGE1/d_re[3][10]/q STAGE1_d_re_reg[3][10]/Q -type DFF DFF
add mapped point STAGE1/d_re[3][11]/q STAGE1_d_re_reg[3][11]/Q -type DFF DFF
add mapped point STAGE1/d_re[3][12]/q STAGE1_d_re_reg[3][12]/Q -type DFF DFF
add mapped point STAGE1/d_re[3][13]/q STAGE1_d_re_reg[3][13]/Q -type DFF DFF
add mapped point STAGE1/d_re[3][14]/q STAGE1_d_re_reg[3][14]/Q -type DFF DFF
add mapped point STAGE1/d_re[3][15]/q STAGE1_d_re_reg[3][15]/Q -type DFF DFF
add mapped point STAGE1/xout_im[0]/q STAGE1_xout_im_reg[0]/Q -type DFF DFF
add mapped point STAGE1/xout_im[1]/q STAGE1_xout_im_reg[1]/Q -type DFF DFF
add mapped point STAGE1/xout_im[2]/q STAGE1_xout_im_reg[2]/Q -type DFF DFF
add mapped point STAGE1/xout_im[3]/q STAGE1_xout_im_reg[3]/Q -type DFF DFF
add mapped point STAGE1/xout_im[4]/q STAGE1_xout_im_reg[4]/Q -type DFF DFF
add mapped point STAGE1/xout_im[5]/q STAGE1_xout_im_reg[5]/Q -type DFF DFF
add mapped point STAGE1/xout_im[6]/q STAGE1_xout_im_reg[6]/Q -type DFF DFF
add mapped point STAGE1/xout_im[7]/q STAGE1_xout_im_reg[7]/Q -type DFF DFF
add mapped point STAGE1/xout_im[8]/q STAGE1_xout_im_reg[8]/Q -type DFF DFF
add mapped point STAGE1/xout_im[9]/q STAGE1_xout_im_reg[9]/Q -type DFF DFF
add mapped point STAGE1/xout_im[10]/q STAGE1_xout_im_reg[10]/Q -type DFF DFF
add mapped point STAGE1/xout_im[11]/q STAGE1_xout_im_reg[11]/Q -type DFF DFF
add mapped point STAGE1/xout_im[12]/q STAGE1_xout_im_reg[12]/Q -type DFF DFF
add mapped point STAGE1/xout_im[13]/q STAGE1_xout_im_reg[13]/Q -type DFF DFF
add mapped point STAGE1/xout_im[14]/q STAGE1_xout_im_reg[14]/Q -type DFF DFF
add mapped point STAGE1/xout_im[15]/q STAGE1_xout_im_reg[15]/Q -type DFF DFF
add mapped point STAGE1/xout_re[0]/q STAGE1_xout_re_reg[0]/Q -type DFF DFF
add mapped point STAGE1/xout_re[1]/q STAGE1_xout_re_reg[1]/Q -type DFF DFF
add mapped point STAGE1/xout_re[2]/q STAGE1_xout_re_reg[2]/Q -type DFF DFF
add mapped point STAGE1/xout_re[3]/q STAGE1_xout_re_reg[3]/Q -type DFF DFF
add mapped point STAGE1/xout_re[4]/q STAGE1_xout_re_reg[4]/Q -type DFF DFF
add mapped point STAGE1/xout_re[5]/q STAGE1_xout_re_reg[5]/Q -type DFF DFF
add mapped point STAGE1/xout_re[6]/q STAGE1_xout_re_reg[6]/Q -type DFF DFF
add mapped point STAGE1/xout_re[7]/q STAGE1_xout_re_reg[7]/Q -type DFF DFF
add mapped point STAGE1/xout_re[8]/q STAGE1_xout_re_reg[8]/Q -type DFF DFF
add mapped point STAGE1/xout_re[9]/q STAGE1_xout_re_reg[9]/Q -type DFF DFF
add mapped point STAGE1/xout_re[10]/q STAGE1_xout_re_reg[10]/Q -type DFF DFF
add mapped point STAGE1/xout_re[11]/q STAGE1_xout_re_reg[11]/Q -type DFF DFF
add mapped point STAGE1/xout_re[12]/q STAGE1_xout_re_reg[12]/Q -type DFF DFF
add mapped point STAGE1/xout_re[13]/q STAGE1_xout_re_reg[13]/Q -type DFF DFF
add mapped point STAGE1/xout_re[14]/q STAGE1_xout_re_reg[14]/Q -type DFF DFF
add mapped point STAGE1/xout_re[15]/q STAGE1_xout_re_reg[15]/Q -type DFF DFF
add mapped point s1r_im[0]/q s1r_im_reg[0]/Q -type DFF DFF
add mapped point s1r_im[1]/q s1r_im_reg[1]/Q -type DFF DFF
add mapped point s1r_im[2]/q s1r_im_reg[2]/Q -type DFF DFF
add mapped point s1r_im[3]/q s1r_im_reg[3]/Q -type DFF DFF
add mapped point s1r_im[4]/q s1r_im_reg[4]/Q -type DFF DFF
add mapped point s1r_im[5]/q s1r_im_reg[5]/Q -type DFF DFF
add mapped point s1r_im[6]/q s1r_im_reg[6]/Q -type DFF DFF
add mapped point s1r_im[7]/q s1r_im_reg[7]/Q -type DFF DFF
add mapped point s1r_im[8]/q s1r_im_reg[8]/Q -type DFF DFF
add mapped point s1r_im[9]/q s1r_im_reg[9]/Q -type DFF DFF
add mapped point s1r_im[10]/q s1r_im_reg[10]/Q -type DFF DFF
add mapped point s1r_im[11]/q s1r_im_reg[11]/Q -type DFF DFF
add mapped point s1r_im[12]/q s1r_im_reg[12]/Q -type DFF DFF
add mapped point s1r_im[13]/q s1r_im_reg[13]/Q -type DFF DFF
add mapped point s1r_im[14]/q s1r_im_reg[14]/Q -type DFF DFF
add mapped point s1r_im[15]/q s1r_im_reg[15]/Q -type DFF DFF
add mapped point s1r_re[0]/q s1r_re_reg[0]/Q -type DFF DFF
add mapped point s1r_re[1]/q s1r_re_reg[1]/Q -type DFF DFF
add mapped point s1r_re[2]/q s1r_re_reg[2]/Q -type DFF DFF
add mapped point s1r_re[3]/q s1r_re_reg[3]/Q -type DFF DFF
add mapped point s1r_re[4]/q s1r_re_reg[4]/Q -type DFF DFF
add mapped point s1r_re[5]/q s1r_re_reg[5]/Q -type DFF DFF
add mapped point s1r_re[6]/q s1r_re_reg[6]/Q -type DFF DFF
add mapped point s1r_re[7]/q s1r_re_reg[7]/Q -type DFF DFF
add mapped point s1r_re[8]/q s1r_re_reg[8]/Q -type DFF DFF
add mapped point s1r_re[9]/q s1r_re_reg[9]/Q -type DFF DFF
add mapped point s1r_re[10]/q s1r_re_reg[10]/Q -type DFF DFF
add mapped point s1r_re[11]/q s1r_re_reg[11]/Q -type DFF DFF
add mapped point s1r_re[12]/q s1r_re_reg[12]/Q -type DFF DFF
add mapped point s1r_re[13]/q s1r_re_reg[13]/Q -type DFF DFF
add mapped point s1r_re[14]/q s1r_re_reg[14]/Q -type DFF DFF
add mapped point s1r_re[15]/q s1r_re_reg[15]/Q -type DFF DFF
add mapped point s1r_valid/q s1r_valid_reg/Q -type DFF DFF
add mapped point s2r_im[0]/q s2r_im_reg[0]/Q -type DFF DFF
add mapped point s2r_im[1]/q s2r_im_reg[1]/Q -type DFF DFF
add mapped point s2r_im[2]/q s2r_im_reg[2]/Q -type DFF DFF
add mapped point s2r_im[3]/q s2r_im_reg[3]/Q -type DFF DFF
add mapped point s2r_im[4]/q s2r_im_reg[4]/Q -type DFF DFF
add mapped point s2r_im[5]/q s2r_im_reg[5]/Q -type DFF DFF
add mapped point s2r_im[6]/q s2r_im_reg[6]/Q -type DFF DFF
add mapped point s2r_im[7]/q s2r_im_reg[7]/Q -type DFF DFF
add mapped point s2r_im[8]/q s2r_im_reg[8]/Q -type DFF DFF
add mapped point s2r_im[9]/q s2r_im_reg[9]/Q -type DFF DFF
add mapped point s2r_im[10]/q s2r_im_reg[10]/Q -type DFF DFF
add mapped point s2r_im[11]/q s2r_im_reg[11]/Q -type DFF DFF
add mapped point s2r_im[12]/q s2r_im_reg[12]/Q -type DFF DFF
add mapped point s2r_im[13]/q s2r_im_reg[13]/Q -type DFF DFF
add mapped point s2r_im[14]/q s2r_im_reg[14]/Q -type DFF DFF
add mapped point s2r_im[15]/q s2r_im_reg[15]/Q -type DFF DFF
add mapped point s2r_re[0]/q s2r_re_reg[0]/Q -type DFF DFF
add mapped point s2r_re[1]/q s2r_re_reg[1]/Q -type DFF DFF
add mapped point s2r_re[2]/q s2r_re_reg[2]/Q -type DFF DFF
add mapped point s2r_re[3]/q s2r_re_reg[3]/Q -type DFF DFF
add mapped point s2r_re[4]/q s2r_re_reg[4]/Q -type DFF DFF
add mapped point s2r_re[5]/q s2r_re_reg[5]/Q -type DFF DFF
add mapped point s2r_re[6]/q s2r_re_reg[6]/Q -type DFF DFF
add mapped point s2r_re[7]/q s2r_re_reg[7]/Q -type DFF DFF
add mapped point s2r_re[8]/q s2r_re_reg[8]/Q -type DFF DFF
add mapped point s2r_re[9]/q s2r_re_reg[9]/Q -type DFF DFF
add mapped point s2r_re[10]/q s2r_re_reg[10]/Q -type DFF DFF
add mapped point s2r_re[11]/q s2r_re_reg[11]/Q -type DFF DFF
add mapped point s2r_re[12]/q s2r_re_reg[12]/Q -type DFF DFF
add mapped point s2r_re[13]/q s2r_re_reg[13]/Q -type DFF DFF
add mapped point s2r_re[14]/q s2r_re_reg[14]/Q -type DFF DFF
add mapped point s2r_re[15]/q s2r_re_reg[15]/Q -type DFF DFF
add mapped point s2r_valid/q s2r_valid_reg/Q -type DFF DFF
add mapped point STAGE1/cnt[0]/q STAGE1_cnt_reg[0]/Q -type DFF DFF
add mapped point STAGE1/cnt[1]/q STAGE1_cnt_reg[1]/Q -type DFF DFF
add mapped point STAGE1/phase/q STAGE1_phase_reg/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
